#!/usr/bin/with-contenv ash

if [ "x$SYNAPSE_CONFIG_DIR" = "x" | "x$SYNAPSE_CONFIG_PATH" = "x" ]; then
    SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    SYNAPSE_CONFIG_DIR=/data
fi

sed -i "s;{SYNAPSE_CONFIG_PATH};$SYNAPSE_CONFIG_PATH;g" /usr/local/bin/synapse-launcher

echo "127.0.0.1 $SYNAPSE_SERVER_NAME" >> /etc/hosts

if [ ! -f $SYNAPSE_CONFIG_PATH ]; then
    mkdir -p $SYNAPSE_CONFIG_DIR
    env /synapse/bin/generate_config_from_template.py
    sleep 20 && /synapse/bin/register_new_matrix_user -u $SYNAPSE_ROOT_USER -p $SYNAPSE_ROOT_PASSWORD -c $SYNAPSE_CONFIG_PATH\
     -a http://$SYNAPSE_SERVER_NAME:8008 &

fi

echo 0 > /tmp/synapse
