#!/usr/bin/with-contenv  sh

if [ "x$SYNAPSE_CONFIG_DIR" == "x" -o "x$SYNAPSE_CONFIG_PATH" == "x" ];
then
    SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    SYNAPSE_CONFIG_DIR=/data
fi

sed -i "s;{SYNAPSE_CONFIG_PATH};$SYNAPSE_CONFIG_PATH;g" /usr/local/bin/synapse-launcher

echo "127.0.0.1 $SYNAPSE_SERVER_NAME" >> /etc/hosts

[ ! -d $SYNAPSE_CONFIG_DIR ] && mkdir -p $SYNAPSE_CONFIG_DIR

env /synapse/bin/generate_config_from_template.py
source /synapse/bin/activate
synctl start $SYNAPSE_CONFIG_PATH
register_new_matrix_user -u $SYNAPSE_ROOT_USER -p $SYNAPSE_ROOT_PASSWORD -c $SYNAPSE_CONFIG_PATH -a http://$SYNAPSE_SERVER_NAME:8008 
synctl stop $SYNAPSE_CONFIG_PATH
echo 0 > /tmp/synapse
